### PR TITLE
feat: implemented automatic maintenance of the 'lang' attribute on components with reactive i18n

### PR DESCRIPTION
**Pull request by mesr**
No surprise, pretty much as proposed. I took the opportunity to fix the `app-with-18n-reactive` e2e test that was not performing its last locale switching.

(this PR implements proposal #56)

### CODE REVIEW

**Review by ducksoupdev — APPROVED** [review]

**Review by ducksoupdev — CHANGES_REQUESTED** [review]
Can you fix the linting errors?

**Comment by mesr** [comment]
For sure, I'll have a look. Thanks for pointing it out.

**Comment by ducksoupdev** [comment]
I have added a Github workflow for running PR checks - that should help with subsequent work :)

**Comment by mesr** [comment]
There seem to be an issue with NPM dependencies. I ran into the same issue on my dev server when running `npm install` after cloning the repo; had to `--force` install.

**Comment by ducksoupdev** [comment]
> There seems to be an issue with NPM dependencies. I ran into the same issue on my dev server when running `npm install` after cloning the repo; had to `--force` install.

@mesr there was a dependency issue. I have fixed it in the main branch so if you rebase your branch, it should be fine.

**Comment by mesr** [comment]
Ah ok, I see. I think it should be fine now.

**Review by ducksoupdev — APPROVED** [review]

**Pull request merged**
